import './globals.css'
import type { Metadata } from 'next'
import { Inter, Oswald, Montserrat } from 'next/font/google'

const oswald = Oswald({ subsets: ['latin'], variable: '--font-heading' })
const montserrat = Montserrat({ subsets: ['latin'], variable: '--font-body' })

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app'
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<html lang='en' className='dark'>
			<body className={`${oswald.variable} ${montserrat.variable}`}>{children}</body>
		</html>
	)
}
